"""initial schema v1

Revision ID: 5a53d56efe9d
Revises: 
Create Date: 2026-09-19 20:04:54.899736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a53d56efe9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('subjects',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_grade'), ['grade'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('chapters',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_subject_id'), ['subject_id'], unique=False)

    op.create_table('exams',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('exam_type', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_student_id'), ['student_id'], unique=False)

    op.create_table('goals',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_value', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_student_id'), ['student_id'], unique=False)

    op.create_table('plans',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_plan_date')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_student_id'), ['student_id'], unique=False)

    op.create_table('resources',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('publisher', sa.String(length=120), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token_jti'), ['token_jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('academic_year', sa.String(length=16), nullable=True),
    sa.Column('target_rank', sa.Integer(), nullable=True),
    sa.Column('target_major', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('student_states',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=64), nullable=True),
    sa.Column('study_condition', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_student_state_date')
    )
    with op.batch_alter_table('student_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_states_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_states_student_id'), ['student_id'], unique=False)

    op.create_table('time_blocks',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('block_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'day_of_week', 'start_time', 'end_time', 'block_type', name='uq_time_block')
    )
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_blocks_student_id'), ['student_id'], unique=False)

    op.create_table('exam_results',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('blank_count', sa.Integer(), nullable=False),
    sa.Column('percent_konkur', sa.Float(), nullable=True),
    sa.Column('percent_no_penalty', sa.Float(), nullable=True),
    sa.Column('difficulty_breakdown', sa.JSON(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_results_exam_id'), ['exam_id'], unique=False)

    op.create_table('learning_activities',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_student_started', ['student_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_activities_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_activities_student_id'), ['student_id'], unique=False)

    op.create_table('topics',
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('questions',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('correct_answer', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index('ix_questions_resource_topic', ['resource_id', 'topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('exam_answers',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'question_id', name='uq_exam_answer')
    )
    with op.batch_alter_table('exam_answers', schema=None) as batch_op:
        batch_op.create_index('ix_exam_answers_exam', ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_answers_exam_id'), ['exam_id'], unique=False)

    op.create_table('exam_questions',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_questions_question_id'), ['question_id'], unique=False)

    op.create_table('question_marks',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('mark_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'question_id', 'mark_type', name='uq_question_mark')
    )
    with op.batch_alter_table('question_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_marks_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_marks_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_question_marks_student_question', ['student_id', 'question_id'], unique=False)

    op.create_table('review_queue',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_queue_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_review_queue_student_status_date', ['student_id', 'status', 'scheduled_date'], unique=False)

    op.create_table('test_records',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('solved_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['learning_activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_records_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_solved_at'), ['solved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_test_records_student_solved', ['student_id', 'solved_at'], unique=False)

    op.create_table('error_notes',
    sa.Column('test_record_id', sa.UUID(), nullable=False),
    sa.Column('error_type', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['test_record_id'], ['test_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_notes_test_record_id'), ['test_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_notes_test_record_id'))

    op.drop_table('error_notes')
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.drop_index('ix_test_records_student_solved')
        batch_op.drop_index(batch_op.f('ix_test_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_test_records_solved_at'))
        batch_op.drop_index(batch_op.f('ix_test_records_question_id'))

    op.drop_table('test_records')
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_review_queue_student_status_date')
        batch_op.drop_index(batch_op.f('ix_review_queue_student_id'))
        batch_op.drop_index(batch_op.f('ix_review_queue_question_id'))

    op.drop_table('review_queue')
    with op.batch_alter_table('question_marks', schema=None) as batch_op:
        batch_op.drop_index('ix_question_marks_student_question')
        batch_op.drop_index(batch_op.f('ix_question_marks_student_id'))
        batch_op.drop_index(batch_op.f('ix_question_marks_question_id'))

    op.drop_table('question_marks')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_exam_questions_exam_id'))

    op.drop_table('exam_questions')
    with op.batch_alter_table('exam_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_answers_exam_id'))
        batch_op.drop_index('ix_exam_answers_exam')

    op.drop_table('exam_answers')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index('ix_questions_resource_topic')
        batch_op.drop_index(batch_op.f('ix_questions_resource_id'))

    op.drop_table('questions')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_chapter_id'))

    op.drop_table('topics')
    with op.batch_alter_table('learning_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_activities_student_id'))
        batch_op.drop_index(batch_op.f('ix_learning_activities_started_at'))
        batch_op.drop_index('ix_activities_student_started')

    op.drop_table('learning_activities')
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_results_exam_id'))

    op.drop_table('exam_results')
    with op.batch_alter_table('time_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_blocks_student_id'))

    op.drop_table('time_blocks')
    with op.batch_alter_table('student_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_states_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_states_date'))

    op.drop_table('student_states')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_jti'))

    op.drop_table('sessions')
    op.drop_table('resources')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_student_id'))
        batch_op.drop_index(batch_op.f('ix_plans_date'))

    op.drop_table('plans')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_student_id'))

    op.drop_table('goals')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_student_id'))

    op.drop_table('exams')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_subject_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_grade'))
        batch_op.drop_index(batch_op.f('ix_subjects_field'))

    op.drop_table('subjects')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
